<!DOCTYPE html>
<html lang="th">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>สุขสันต์วันเกิดที่รัก!</title>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Poppins', sans-serif;
      margin: 0;
      padding: 0;
      background: linear-gradient(135deg, #fce4ec, #f8bbd0);
      color: #333;
      overflow-x: hidden;
    }

    h1, h2, h3 {
      color: #e94e77;
      text-align: center;
    }

    /* ป๊อปอัป */
    .popup {
      display: none;
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.7);
      justify-content: center;
      align-items: center;
      z-index: 1000;
    }

    .popup-content {
      background-color: white;
      padding: 40px;
      border-radius: 10px;
      text-align: center;
      animation: popupFadeIn 1s ease-out;
      position: relative;
      max-width: 80%;
    }

    .popup-content h2 {
      font-size: 36px;
      color: #e94e77;
    }

    .popup-content p {
      font-size: 20px;
      margin-top: 20px;
    }

    .popup-content button {
      background-color: #e94e77;
      color: white;
      padding: 12px 24px;
      border: none;
      border-radius: 5px;
      font-size: 18px;
      cursor: pointer;
      margin-top: 20px;
    }

    .popup-content button:hover {
      background-color: #d44365;
    }

    /* ส่วนของข้อความต้อนรับ */
    h1 {
      font-size: 50px;
      text-align: center;
      margin-top: 80px;
      animation: fadeIn 3s ease-out;
    }

    p {
      font-size: 20px;
      text-align: center;
      margin-top: 20px;
      color: #555;
      animation: fadeIn 2s ease-out;
    }

    /* ฟอนต์สำหรับข้อความยาว */
    .main-message {
      text-align: center;
      margin-top: 50px;
      font-size: 22px;
      color: #444;
      animation: slideIn 2s ease-out;
      padding: 20px;
      line-height: 1.6;
    }

    @keyframes fadeIn {
      0% { opacity: 0; }
      100% { opacity: 1; }
    }

    @keyframes slideIn {
      0% { transform: translateY(50px); opacity: 0; }
      100% { transform: translateY(0); opacity: 1; }
    }

    /* การแสดงแกลเลอรี่ */
    .gallery {
      display: flex;
      justify-content: center;
      flex-wrap: wrap;
      margin-top: 50px;
    }

    .gallery h2 {
      width: 100%;
      text-align: center;
      margin-bottom: 20px;
    }

    .gallery img {
      max-width: 300px;
      width: 100%;
      height: auto;
      margin: 15px;
      border-radius: 10px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      transition: transform 0.3s ease-in-out;
      opacity: 0;
      animation: fadeInGallery 1s ease-in-out forwards;
    }

    .gallery img:nth-child(1) {
      animation-delay: 0.5s;
    }

    .gallery img:nth-child(2) {
      animation-delay: 1s;
    }

    .gallery img:nth-child(3) {
      animation-delay: 1.5s;
    }

    .gallery img:nth-child(4) {
      animation-delay: 2s;
    }

    @keyframes fadeInGallery {
      0% { opacity: 0; }
      100% { opacity: 1; }
    }

    /* ปรับขนาดให้เหมาะสมในมือถือ */
    @media (max-width: 768px) {
      h1 {
        font-size: 40px;
      }

      .main-message {
        font-size: 18px;
      }

      .gallery img {
        max-width: 90%;
      }

      .popup-content {
        width: 90%;
        padding: 20px;
      }

      iframe {
        width: 100%;
        height: 250px;
      }
    }

    /* ส่วนของการแสดงข้อความ */
    .extra-message {
      text-align: center;
      margin-top: 50px;
      font-size: 22px;
      color: #555;
      animation: fadeIn 2s ease-out;
      line-height: 1.6;
    }

    /* ส่วนที่ใส่เพลง */
    audio {
      width: 100%;
      margin-top: 30px;
      border-radius: 5px;
    }

    /* ส่วนที่ใส่คลิป */
    iframe {
      width: 100%;
      height: 300px;
      margin-top: 30px;
      border-radius: 10px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
    }

  </style>
  <script>
    // ฟังก์ชันสำหรับแสดงป๊อปอัป
    window.onload = function() {
      setTimeout(function() {
        document.getElementById("popup").style.display = "flex";
      }, 1000); // ป๊อปอัปจะแสดงหลังจากโหลดหน้าเว็บไซต์ 2 วินาที

      // ปิดป๊อปอัป
      document.getElementById("closePopup").onclick = function() {
        document.getElementById("popup").style.display = "none";
      };
    }
  </script>
</head>
<body>

  <!-- ป๊อปอัป -->
  <div id="popup" class="popup">
    <div class="popup-content">
      <h2>สุขสันต์วันเกิดที่รัก!</h2>
      <p>วันนี้เป็นวันที่พิเศษมากๆ เพราะมันคือวันเกิดของคุณ! ขอให้คุณมีความสุขในทุกๆ วัน!</p>
      <button id="closePopup">กดปิดได้เลยนะคะถ้าอ่านจบแล้ว</button>
    </div>
  </div>

  <!-- ส่วนต้อนรับ -->
  <section class="hero">
    <h1>สุขสันต์วันเกิดที่รัก!</h1>
    <p>วันนี้เป็นวันที่พิเศษสำหรับเรา เพราะมันคือวันเกิดของคุณที่เราจะเฉลิมฉลองไปด้วยกันในทุกๆ ช่วงเวลา</p>
  </section>

  <!-- ข้อความที่มีความหมาย -->
  <section class="main-message">
    <p>ที่รัก, การที่เราได้ใช้ชีวิตไปด้วยกันในทุกๆ วันคือสิ่งที่ฉันขอให้เกิดขึ้นตลอดไป วันนี้เป็นวันเกิดของคุณ ฉันขอให้ทุกๆ ความฝันของคุณเป็นจริง และขอให้คุณมีความสุขอย่างที่สุดในโลกนี้ค่ะ</p>
    <p>วันนี้ไม่ใช่แค่การเฉลิมฉลองวันเกิด แต่ยังเป็นการเฉลิมฉลองความรักที่เราได้มีให้กันตลอดมา ขอให้ทุกๆ วันของเราจะเต็มไปด้วยรอยยิ้ม และความรักที่มั่นคงตลอดไป ฉันรักคุณมากๆ ค่ะ 💖</p>
  </section>

  <!-- แกลเลอรี่ภาพ -->
  <section class="gallery">
    <h2>ภาพความทรงจำที่เรามีร่วมกัน</h2>
    <div class="gallery-container">
      <img src="C:\Users\airly\Desktop\828f8d0c-fa2e-4dec-9fb0-a875dada70fd.jfif" alt="Moment 1">
      <img src="C:\Users\airly\Desktop\cd025c43-9caf-4788-901c-d3f87e69f8ce.jpg" alt="Moment 2">
      <img src="C:\Users\airly\Desktop\d6022d98-7756-4cd4-bdee-58245e66641c.jpg" alt="Moment 3">
      <img src="C:\Users\airly\Pictures\65d28dcfe196cdf4588af1d77307d196.jpg" alt="Moment 4">
    </div>
  </section>

<!DOCTYPE html>
<html lang="th">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>สุขสันต์วันเกิดที่รัก!</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #f8bbd0;
      margin: 0;
      padding: 0;
      text-align: center;
    }
    h1 {
      color: #e94e77;
      font-size: 40px;
      margin-top: 50px;
    }
    audio {
      display: none; /* ซ่อนตัวเล่นเสียง */
    }
  </style>
</head>
<body>
  <h1>สุขสันต์วันเกิดที่รัก!</h1>

  <!-- แทรกไฟล์เพลง DWASM ที่เล่นอัตโนมัติและไม่มีปุ่มควบคุม -->
  <section class="music">
    <h2>เพลง "Die with a Smile" (DWASM)</h2>
    <audio autoplay loop>
      <source src="DWASM.mp3" type="audio/mp3">
      <source src="DWASM.ogg" type="audio/ogg">
      Your browser does not support the audio element.
    </audio>
  </section>

</body>
</html>


  <!-- ข้อความเพิ่มเติม -->
  <section class="extra-message">
    <p>ในทุกๆ วันที่เรามีความสุขร่วมกัน ฉันรู้สึกขอบคุณที่มีคุณอยู่เคียงข้าง และในวันนี้ ฉันอยากจะบอกคุณว่า... ฉันจะรักคุณตลอดไปค่ะ 💖</p>
  </section>

</body>
</html>
